sonar.projectKey=sonaibabi_npm_projects
sonar.organization=sonaibabi

sonar.sources=.
sonar.exclusions=node_modules/**,k8s/**,Dockerfile
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
