name: Build Docker Images
on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types: [ completed ]
jobs:
  trigger-build:
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
    
      - id: changed
        uses: tj-actions/changed-files@v45
        with:
          dir_names: true
          files: |
            services/**

      - id: set-matrix
        run: |
         if [ -z "${{ steps.changed.outputs.all_changed_files }}" ]; then
         echo 'services=[]' >> $GITHUB_OUTPUT
         else
         SERVICES=$(echo "${{ steps.changed.outputs.all_changed_files }}" \
         | jq -R -s -c 'split("\n") | map(select(length>0) | sub("^services/"; ""))')
         echo "services=$SERVICES" >> $GITHUB_OUTPUT
         fi
      
      - name: Build images
        if: steps.set-matrix.outputs.services != '[]'
        uses: ./.github/workflows/reusable-build.yml
        with:
          services: ${{ steps.set-matrix.outputs.services }}
          secrets:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
