name: CI on pull request
on:
  push:
  pull_request:
    types: [ opened ]
jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.set-matrix.outputs.services }}

    steps:
      - uses: actions/checkout@v4

      - id: changed
        uses: tj-actions/changed-files@v45
        with:
          dir_names: true
          files: |
            services/**

      - id: set-matrix
        run: |
         if [ -z "${{ steps.changed.outputs.all_changed_files }}" ]; then
         echo 'services=[]' >> $GITHUB_OUTPUT
         else
         SERVICES=$(echo "${{ steps.changed.outputs.all_changed_files }}" \
         | jq -R -s -c 'split("\n") | map(select(length>0) | sub("^services/"; ""))')
         echo "services=$SERVICES" >> $GITHUB_OUTPUT
         fi

  build-and-scan:
    needs: detect-changes
    if: needs.detect-changes.outputs.services != '[]'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ${{ fromJson(needs.detect-changes.outputs.services) }}
    defaults:
      run:
        working-directory: services/${{ matrix.service }}
    steps:
    - uses: actions/checkout@v4

    - name: Debug service name
      run: echo "Building service ${{ matrix.service }}"

    - uses: actions/setup-node@v4
      with:
        node-version: "20"

    - run: npm ci
    - run: npm test
