name: CI on pull request
on:
  push:
  pull_request:
    types: [ opened ]
jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - uses: actions/checkout@v4

      - id: changed
        uses: tj-actions/changed-files@v45
        with:
          dir_names: true
          files: |
            services/**

      - id: set-matrix
        run: |
          echo "matrix=$(jq -nc --argjson files '${{ steps.changed.outputs.all_changed_files }}' \
          '{service: $files}')" >> $GITHUB_OUTPUTS
  build-and-scan:
    needs: detect-changes
    if: needs.detect-changes.outputs.matrix != ''
    runs-on: ubuntu-latest

    strategy:
      matrix: ${{ fromJson(needs.detect-changes.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v4

      - name: Build service
        working-directory: services/${{ matrix.service }}
        run: |
          npm ci
          npm test
      - name: Sonar Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: services/${{ matrix.service }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
