name: Reusable Detect Changes

on:
  workflow_call:
    outputs:
      services:
        description: "Changed services"
        value: ${{ jobs.detect.outputs.services }}

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.set-matrix.outputs.services }}

    steps:
      - uses: actions/checkout@v4

      - id: changed
        uses: tj-actions/changed-files@v45
        with:
          dir_names: true
          files: |
            services/**

      - id: set-matrix
        run: |
          if [ -z "${{ steps.changed.outputs.all_changed_files }}" ]; then
            echo 'services=[]' >> $GITHUB_OUTPUT
          else
            SERVICES=$(echo "${{ steps.changed.outputs.all_changed_files }}" \
              | jq -R -s -c 'split("\n") | map(select(length>0) | sub("^services/"; ""))')
            echo "services=$SERVICES" >> $GITHUB_OUTPUT
          fi
